### PR TITLE
CMake refactor: adhere to Modern CMake standards.

### PR DESCRIPTION
**Pull request by guacke**
We have encountered some problems with the Libcint installation (mostly on Mac OS systems). This PR modernizes the CMake configuration and fixes the problems we encountered.

### CODE REVIEW

**Comment by guacke** [comment]
The above commits were required to get Libcint installed on our HPC clusters.

**Comment by sunqm** [comment]
> We have encountered some problems with the Libcint installation (mostly on Mac OS systems). This PR modernizes the CMake configuration and fixes the problems we encountered.

What's the problem you got? The cmake config should be compatible for both cmake 2.* and 3.*

**Comment by guacke** [comment]
The problems encountered were related to missing symbols in the shared libraries (I will file a bug report as an issue). As this PR imposes that users have at least CMake 3.13 installed and you would like to support both CMake 2 and 3, I will close this pull request.

**Comment by sunqm** [comment]
Do you see the problem on other macs or just the one with cmake 3.13? There is no error on my mac running cmake 3.12.3

**Pull request closed without merging**
