### PR TITLE
True quad precision gamma inc like

### PR DESCRIPTION
**Pull request by jeffhammond**
Do you want me to implement `__float128` everywhere?

### CODE REVIEW

**Comment by sunqm** [comment]
That'd be great to have true 128 bit float.   __float128 is gcc specific attribute, is it also available for other popular compilers: clang, pgi?

**Comment by sunqm** [comment]
Looks lgamma_like_inc not defined if HAVE_QUADMATH_H was not found?

**Comment by jeffhammond** [comment]
GCC and Intel support `__float`.  Intel used to support `_Quad` but switched to `__float128` at some point.  I don't know the specifics but I have used it.

In any case, implementing a CMake query for this feature is the right way to go.  Elemental does this already and we can refer to https://github.com/elemental/Elemental/blob/master/cmake/external_projects/ElMath.cmake for the right way to do it.

If you want to support older Intel compilers, then the right thing to do is typedef a quad precision type to `__float128` or `_Quad` based upon what is available.

I'll look up what IBM POWER supports for 128b floats.

**Comment by jeffhammond** [comment]
Sorry, I was sloppy and hard-coded `HAVE_QUADMATH_H` because I haven't written the CMake test for it yet.  You should not merge this PR until I resolve that.

**Comment by jeffhammond** [comment]
I'll work on the CMake test ASAP.  For now, you should document that one needs to manually disable `HAVE_QUADMATH_H` with Clang or other compilers that don't support `__float128`.

**Pull request closed without merging**
